version: 2

models:
  - name: int_ticket_sales_dedup
    description: "Intermediate model with latest ticket sale per ticket_sales_key"
    columns:
      - name: ticket_sales_key
        tests:
          - not_null
          - unique
      - name: timestamp
        tests:
          - not_null
      - name: tickets_sold
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null

