name: fanalyze
version: "2.0"
profile: fanalyze

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target"]

models:
  fanalyze:
    01_staging:
      +materialized: view
      +schema_suffix: ""

      setlistfm_data:
        +materialized: view
        +schema_suffix: ""
        
    02_intermediate:
      +materialized: table
    03_marts:
      +materialized: table
