name: fanalyze
version: 1.0.0
config-version: 2

profile: fanalyze

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  "01_staging":
    setlistfm_data:
      +materialized: view

  "02_intermediate":
    +materialized: ephemeral

  "03_marts":
    core:
      +materialized: table
    fan_behavior:
      +materialized: table
