version: 2

models:
  - name: stg_shows
    description: "Cleaned and typed version of raw show data from setlist.fm"
    columns:
      - name: show_id
        description: "Unique ID for the show"
        tests:
          - not_null
          - unique

      - name: artist_name
        description: "Name of the band"

      - name: event_date
        description: "Date of the concert"
