version: 2
sources:
- name: setlistfm
  database: FANALYZE
  schema: PUBLIC
  tables:
  - name: staging_shows
    description: Raw show-level concert data from setlist.fm
  - name: staging_setlists
    description: Raw setlist data in nested JSON format
