# models/01_staging/setlistfm_data/sources.yml

version: 2

sources:
  - name: setlistfm_data
    database: DB_FANALYZE
    schema: fanalyze
    description: "Source data from Setlist.fm"
    tables:
      - name: stg_shows_raw
      - name: stg_setlists_raw
