# models/01_staging/setlistfm_data/sources.yml

version: 2

sources:
  - name: setlistfm_data
    schema: FANALYZE
    tables:
      - name: stg_setlists_raw
      - name: stg_setlists_sch
      - name: stg_shows_raw          # <-- Add this
      - name: stg_shows_sch          # <-- And this

