
/* -- Create FACT_ARTISTS (static data, usually manually inserted)
CREATE OR REPLACE TABLE FANALYZE.PUBLIC.FACT_ARTISTS (
  ARTIST_ID STRING PRIMARY KEY,
  ARTIST_NAME STRING,
  ARTIST_GENRE STRING
);
*/
-- Create STAGING_SHOWS
CREATE OR REPLACE TABLE FANALYZE.PUBLIC.STAGING_SHOWS (
  SHOW_ID STRING,
  ARTIST_ID STRING,
  ARTIST_NAME STRING,
  SHOW_DATE DATE,
  VENUE STRING,
  CITY STRING,
  COUNTRY STRING,
  TOUR_NAME STRING,
  TICKET_TIER STRING,
  SIMULATED_PRICE_USD FLOAT
);

-- Create STAGING_SETLISTS
CREATE OR REPLACE TABLE FANALYZE.PUBLIC.STAGING_SETLISTS (
  SHOW_ID STRING,
  SETLIST VARIANT
);

-- Create FACT_SHOWS
CREATE OR REPLACE TABLE FANALYZE.PUBLIC.FACT_SHOWS (
  SHOW_ID STRING PRIMARY KEY,
  ARTIST_ID STRING,
  SHOW_DATE DATE,
  VENUE STRING,
  CITY STRING,
  COUNTRY STRING,
  TOUR_NAME STRING,
  TICKET_TIER STRING,
  SIMULATED_PRICE_USD FLOAT
);

-- Create FACT_SETLISTS
CREATE OR REPLACE TABLE FANALYZE.PUBLIC.FACT_SETLISTS (
  SHOW_ID STRING,
  SONG_NAME STRING,
  SONG_POSITION INT
);

-- Create FACT_SONG_STATS
CREATE OR REPLACE TABLE FANALYZE.PUBLIC.FACT_SONG_STATS (
  ARTIST_ID STRING,
  SONG_NAME STRING,
  PLAY_COUNT INT
);
